# 友情链接状态检测工具配置文件

# 数据源配置
source:
  # 友情链接数据源URL
  url: "https://www.xrbk.cn/api/links.json"
  # 数据源请求头
  headers:
    Accept: "application/json"
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"

# 检测配置
detection:
  # 并发批次大小
  batch_size: 10
  # 批次间延迟（毫秒）
  batch_delay: 200
  # 单个链接检测超时时间（毫秒）
  timeout: 30000
  # 成功状态码范围（最小值）
  success_status_min: 200
  # 成功状态码范围（最大值）
  success_status_max: 399

# 检测请求头配置
request_headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 (check-flink/1.0; +https://links.ityr.xyz/bot)"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
  Accept-Language: "zh-CN,zh;q=0.9"
  Accept-Encoding: "gzip, deflate, br"
  Connection: "keep-alive"
  X-Check-Flink: "1.0"

# 输出配置
output:
  # 输出目录
  directory: "./page"
  # 是否生成HTML报告
  generate_html: true
  # 是否保存错误计数
  save_error_count: true

# 时区配置
timezone:
  # 时区偏移（小时）
  offset: 8
  # 时区名称
  name: "Asia/Shanghai" 