name: 检测友情链接状态

on:
  schedule:
    # 每6小时运行一次
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main, master ]

jobs:
  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 安装依赖
      run: npm install
      
    - name: 检测链接状态
      run: npm run check
      
    - name: 保存检测结果
      run: |
        echo "检测结果已保存到 output/ 文件夹"
        ls -la output/
        echo "文件内容预览:"
        echo "=== status.json ==="
        head -20 output/status.json
        echo "=== status-cf.json ==="
        head -10 output/status-cf.json
        echo "=== status-xiaoxiao.json ==="
        head -10 output/status-xiaoxiao.json 
