name: 检测友情链接状态

on:
  schedule:
    # 每6小时运行一次
    - cron: '*/15 * * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main, master ]

permissions:
  contents: write  # 添加写入权限

jobs:
  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # 获取完整历史
      
    - name: 设置Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 安装依赖
      run: npm install
      
    - name: 检测链接状态
      run: |
        echo "开始检测友情链接状态..."
        npm run check
        echo "检测完成！"
      
    - name: 保存检测结果
      run: |
        echo "检测结果已保存到 page/ 文件夹"
        ls -la page/
        echo "文件内容预览:"
        echo "=== status.json ==="
        head -20 page/status.json
        echo "=== error-count.json ==="
        head -10 page/error-count.json
        
    - name: 配置Git用户
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: 检出page分支
      run: |
        # 尝试检出page分支，如果不存在则创建
        git checkout -b page 2>/dev/null || git checkout page
        # 尝试拉取远程更改，如果失败则重置分支
        git pull origin page || (echo "无法拉取远程更改，重置分支" && git reset --hard HEAD)
        
    - name: 提交检测结果到page分支
      run: |
        # 清空page分支内容（保留.git目录）
        find . -mindepth 1 -not -path './.git*' -not -path './page*' -delete
        # 移动page目录内容到根目录
        mv page/* . 2>/dev/null || true
        rmdir page 2>/dev/null || true
        # 添加所有文件
        git add .
        # 提交更改
        git commit -m "更新链接检测结果 - $(date '+%Y-%m-%d %H:%M:%S')" || echo "没有新的更改"
        # 尝试推送到page分支，如果失败则强制推送
        git push origin page || git push origin page --force-with-lease
        
    - name: 上传检测结果作为Artifact
      uses: actions/upload-artifact@v4
      with:
        name: link-status-results
        path: |
          page/
          *.json
          *.html
          *.png
        retention-days: 30 


