name: 检测友情链接状态

on:
  schedule:
    # 每6小时运行一次
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main, master ]

permissions:
  contents: write  # 添加写入权限

jobs:
  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # 获取完整历史
      
    - name: 设置Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 安装依赖
      run: npm install
      
    - name: 检测链接状态
      run: npm run check
      
    - name: 保存检测结果
      run: |
        echo "检测结果已保存到 output/ 文件夹"
        ls -la output/
        echo "文件内容预览:"
        echo "=== status.json ==="
        head -20 output/status.json
        echo "=== status-cf.json ==="
        head -10 output/status-cf.json
        echo "=== status-xiaoxiao.json ==="
        head -10 output/status-xiaoxiao.json
        
    - name: 配置Git用户
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: 提交检测结果到主分支
      run: |
        # 复制检测结果到根目录
        cp -r output/* ./
        # 添加所有文件
        git add .
        # 提交更改
        git commit -m "更新链接检测结果 - $(date '+%Y-%m-%d %H:%M:%S')" || echo "没有新的更改"
        # 推送到主分支
        git push origin ${{ github.ref_name }}
        
    - name: 上传检测结果作为Artifact
      uses: actions/upload-artifact@v4
      with:
        name: link-status-results
        path: output/
        retention-days: 30 
